version: '3.4'

services:
  zoo:
    image: zookeeper:3.4.9
    restart: unless-stopped
    hostname: zoo
    container_name: zoo
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo:2888:3888
    volumes:
      - zzo-data-volume:/data
      - zzo-datalog-volume:/datalog

  kafka:
    image: confluentinc/cp-kafka:5.3.1
    restart: unless-stopped
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CREATE_TOPICS: "current-final-rating-bu:1:1,current-final-rating-ame:1:1,current-final-rating-age:1:1"
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-volume:/var/lib/kafka/data
    depends_on:
      - zoo

  kafka-ui:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    hostname: kafka-ui
    container_name: kafka-ui
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:19092
    depends_on:
      - kafka 
      - zoo 

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: "1l&gr@"
      POSTGRES_DB: log_ingestion_db
      POSTGRES_USER: ilegra
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data 
      
  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-admin
    hostname: pg-admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: "sw-architect@ilegra.com"
      PGADMIN_DEFAULT_PASSWORD: "1l&gr@"
    ports:
      - "8082:80"
    expose:
      - "8082"
    depends_on:
      - postgres
    volumes:
      - pg-admin-volume:/var/lib/pgadmin

volumes:
  kafka-volume:
    external: false
  zzo-data-volume:
    external: false
  zzo-datalog-volume:
    external: false
  postgres-volume:
    external: false
  pg-admin-volume:
    external: false

